<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.0.1 (Python 3.12.4 on win32)" generated="2024-07-16T01:36:17.119687" rpa="false" schemaversion="5">
<suite id="s1" name="Login" source="D:\ProecjtRobot\Testcase\User\Login.robot">
<test id="s1-t1" name="Login with user ${userName} and password ${password}" line="11">
<status status="FAIL" start="2024-07-16T01:36:17.341068" elapsed="0.000996">Test cannot be empty.</status>
</test>
<status status="FAIL" start="2024-07-16T01:36:17.120657" elapsed="0.222406"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Login">Login</stat>
</suite>
</statistics>
<errors>
<msg time="2024-07-16T01:36:17.335085" level="ERROR">[ DataDriver ] Error in robot file:
  File "D:\ProecjtRobot\Testcase\User\Login.robot", line 0</msg>
<msg time="2024-07-16T01:36:17.336081" level="ERROR">In source file:
  File "datas/users12.csv", line 0</msg>
<msg time="2024-07-16T01:36:17.339074" level="ERROR">Calling method '_start_suite' of listener 'DataDriver' failed: ValueError: Unassigned requiered argument detected: ${userName}.</msg>
</errors>
</robot>
